### ISSUE TITLE
[Actividad 1] Recomendación para mostrar las imágenes y posible feedback

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [PUC-Infovis/syllabus-2019#1]
Hola! 
1. ¿Existe alguna restricción para la actividad de lo que se puede usar? Entiendo que es un ejercicio no evaluado y que hay quizá más de una forma de hacerlo, pero voy al hecho de si se busca poner en práctica lo que vimos ayer en la clase o puede ser algo distinto también, o más bien si se recomienda hacerlo.
2. ¿Pueden dar feedback de las actividades aunque no sean evaluadas y/o mandar una posible solución para comparar y así aprender de los errores o de mejores/distintas formas de hacerlo?

Gracias!
Saludos

**Comment by eiherrera** [comment]
Hola!

1. No hay ninguna restricción de lo que se puede usar. De todas formas, hay maneras más estándar de cómo realizar ciertas cosas. Por ejemplo, para centralizar contenido mediante CSS se suele utilizar [flex](https://css-tricks.com/snippets/css/a-guide-to-flexbox/).
2. Voy a subir una solución a la actividad hoy o a más tardar el Lunes.

Saludos!

**Comment by AlfonsoIgnacioV** [comment]
Gracias!
