### ISSUE TITLE
Duda con presentación de resultados [T01]

### ISSUE THREAD

**Issue by gatochico** [PUC-Infovis/syllabus-2019#10]
Hola! 

Con respecto a la parte de Presentación de resultados, en específico el punto 1: ¿Hay que incluir una explicación también del preprocesamiento y entrenamiendo/predicción de clases de la parte 1 y 2, o es sólo de la obtención de los gráficos una vez todo lo anterior está realizado? Si es lo primero, todavía no me queda claro el nivel de especificidad de la explicación: Por ejemplo, debería poner partes textuales de mi código y explicarlas, o simplemente decir a grandes rasgos que hace el código, o algún punto medio...

Gracias de antemano!

**Comment by Hernan4444** [comment]
¡Hola!

Respecto a tu primera duda, no es necesario explicar el preprocesamiento. Puedes partir desde el archivo que ya tiene los datos limpios y la idea de este apartado es hacer un resumen de los pasos que realizaste en tus códigos para obtener los gráficos que muestras en la página. Puedes asumir que los ayudantes conocen todos los comandos utilizados y por lo tanto, solo puedes mencionarlos si crees que son relevantes para explicar tus pasos. 

Por ejemplo, una explicación para una visualización puede ser:

> Se abre el archivo __datos.csv__, se usa la librería X para calcular ciertos datos a traves del tiempo. Luego se ingresa dichos resultados a la función `plot` de matplotlib para hacer el gráfico de línea. Además se usan otros comandos para agregar leyenda, título y nombre de ejes. Para hacer la matriz de precisión que ocupa 9 gráficos, se creó un objeto `subplot` de 3x3 y para cada posición de ese objeto, se insertó un gráfico con la función `plot`.

Lo importante es que el ayudante logre entender de tu explicación:
1. Qué archivos se utilizaron para hacer funcionar el código.
2. Si es que se ocuparon archivos intermedios. Por ejemplo, una función genera un .csv especial que otra función ocupa. Mencionar eso para que el ayudante esté al tanto que si no está ese .csv, puede caerse el código.
3. Qué funciones se ocuparon para generar el gráfico. Así, si el ayudante quiere editar por ejemplo el título, sepa a donde ir.
4. Cuál fue el orden seguido para hacer todos los gráficos: tras abrir el archivo, se generó la línea del gráfico de línea, luego los nombres de ejes, ..., finalmente se exportó como imagen PNG. En caso de usar una aplicación como Tableau, indicar que tras generar el CSV adecuado, se exportaron los datos a Tableau, se seleccionó la opción de gráfico de línea, se indicó que columnas iban a ser cada eje, ... , finalmente se sacó un pantallazo del gráfico exportado.

Espero haber guiado más tu duda con esta explicación.
Saludos :v:

ps: usé gráfico de línea como ejemplo para no dar tanta pistas con los gráficos solicitados.
