### ISSUE TITLE
Cantidad de datos correctos

### ISSUE THREAD

**Issue by Regenschrim** [PUC-Infovis/syllabus-2019#11]
¿Es posible que nos digan la cantidad de datos que están correctos en ambos dataset, para saber si es que nuestro preprocesamiento esta correcto? Recuerdo que los dijeron en clases, pero solo me calza uno de ellos y no veo error en el que no me calza la cantidad, aunque puede que lo haya anotado mal :s

Gracias!

**Comment by Hernan4444** [comment]
Hola, despues de preprocesar, quedarán 100 datos para entrenar y 50 para predecir.

Saludos :v:
