### ISSUE TITLE
Cantidad de detalles en informe

### ISSUE THREAD

**Issue by jcechavarri** [PUC-Infovis/syllabus-2019#12]
Hola!
Quería saber hasta que nivel de detalle es suficiente en el informe, en el enunciado se piden "explicaciones de alto nivel" pero en la pauta se pide mencionar todos los métodos de las librerías utilizadas.

Mi pregunta es si es necesario explicar todas las funciones o sólo las principales.
Gracias!

**Comment by Hernan4444** [comment]
¡Hola!

Creo que esta issue (#10) responde tu duda. Si no queda algo claro, por favor comentar en esa issue para concentrar las dudas de ese apartado en solo 1 issue.

Saludos ✌️
