### ISSUE TITLE
Normalización datos y parámetros modelos

### ISSUE THREAD

**Issue by fivaldivia** [PUC-Infovis/syllabus-2019#13]
Hola, primero quería saber si es necesario normalizar las bases de datos antes de reducir dimensionalidad? O no es necesario?
Luego, en cuanto a los parámetros de los distintos modelos, es necesario otrogárselos a la hora de entrenarlos o tampoco será evaluado esto?
Muchas gracias.

**Comment by Hernan4444** [comment]
¡Hola!

No es necesario normalizar para esta tarea. En relación a los parámetros, no es necesario otorgarlos y se usarán los por defecto, lo cual está bien. Si deseas realizar el tercer bonus, ahí si será necesario que entregues diversos parámetros al momento de entrenar para calcular las respectivas métricas.

Saludos :v:
