### ISSUE TITLE
[Ayudantia 03] Problema con Cors Request

### ISSUE THREAD

**Issue by KnowYourselves** [PUC-Infovis/syllabus-2019#15]
Hola!

Al intentar probar el script 6 y 7 de la ayudantía 3 de D3 me sale un error por intentar hacer un CORS request en vez de uno http/https al momento de acceder al archivo json. Alguna forma de arreglar esto?

Gracias!

**Comment by eiherrera** [comment]
Hola!

Eso ocurre por motivos de seguridad en los navegadores modernos. Una posible forma de trabajar con archivos locales en el navegador es montar un servidor, lo cual es sencillo de lograr con python 3. Ingresa `python3 -m http.server` en el terminal y tendrás un servidor local en `http://localhost:8000/`.

Saludos!

**Comment by KnowYourselves** [comment]
Me funciono perfect!
