### ISSUE TITLE
Grupo: proyecto del curso.

### ISSUE THREAD

**Issue by jtcaraball** [PUC-Infovis/syllabus-2019#16]
Hola! Hay algún grupo al que le haga falta un integrante? Mi nombre es José Thomas y me cambié de carrera este año así que no conozco a nadie en el curso 😢.
Si bien soy medio noob en machine learning, ya cursé programación avanzada y he tomado ramos de estetica y dibujo vectorial!
Estaba interesado en la visualización de datos para no expertos, pero no estoy apegado a la idea por lo que no tengo problema en trabajar en otro enfoque.

Muchas gracias por leer esto!
Saludos.

**Comment by Hernan4444** [comment]
¡Hola! 
Te recomiendo mandar un mensaje vía webcurso a todos los alumnos, así todos se enterarán de tu issue porque dada la cantidad de **watch** que tiene el repo, puede que pocos lo vean ahora.

Saludos ✌️
