### ISSUE TITLE
[T01] - Mencionar Funciones Utilizadas

### ISSUE THREAD

**Issue by KnowYourselves** [PUC-Infovis/syllabus-2019#19]
Hola!

En la distribución de puntaje se especifica que se deben mencionar las funciones utilizadas en nuestro programa. Qué tan exhaustivo debe ser esto?, Debemos mencionar **todas** las funciones, o solo hacer un desglose de las más importantes?

Gracias!

**Comment by Hernan4444** [comment]
¡Hola!

Creo que esta issue (#10) responde tu duda. Si no queda algo claro, por favor comentar en esa issue para concentrar las dudas de ese apartado en solo 1 issue 😃 .

Saludos ✌️

**Comment by KnowYourselves** [comment]
Sorry y thanks ❤️
