### ISSUE TITLE
[T01] - Duda gráficos

### ISSUE THREAD

**Issue by fdominguezclaro** [PUC-Infovis/syllabus-2019#20]
Hola!

Parece que no estoy entendiendo bien la primera opción de gráficos que se pide hacer. Dicen que serían un total de **3 gráficos,** pero sólo tenemos que graficar el `precisión` y `recall`. Por lo tanto hay algo que no me calza.

--- 

**Por lo que entendí:**
El primer gráfico tendría 3 grupos. 
- Grupo 1: precisión de modelo 1 para clases 0, 1 y 2.
- Grupo 2: precisión de modelo 2 para clases 0, 1 y 2.
- Grupo 3: precisión de modelo 3 para clases 0, 1 y 2.

El segundo gráfico tendría 3 grupos. 
- Grupo 1: recall de modelo 1 para clases 0, 1 y 2.
- Grupo 2: recall de modelo 2 para clases 0, 1 y 2.
- Grupo 3: recall de modelo 3 para clases 0, 1 y 2.

Y el tercero?

**Comment by Hernan4444** [comment]
¡Hola!
El tercer gráfico sería uno de barra normal que cada barra será el _acurracy_ de cada modelo.

Saludos :v:
