### ISSUE TITLE
Proyecto -  Acceso al formulario

### ISSUE THREAD

**Issue by joseluishaddad** [PUC-Infovis/syllabus-2019#21]
Estimados, no puedo acceder al formulario para ver los temas disponibles. Tampoco me pregunta pide ingresar con una cuenta @uc.cl.
Adjunto pantallazo:
![image](https://user-images.githubusercontent.com/20782393/63643968-846d3400-c6aa-11e9-8baf-effb7110524e.png)

**Comment by eiherrera** [comment]
Hola!
¿Qué te muestra si borras `/formrestricted?edit_requested=true` del link?

**Comment by joseluishaddad** [comment]
si lo intenté... se vuelve a poner solo :/

**Comment by eiherrera** [comment]
¿Y si ingresas desde una ventana de incógnito te redirige al mismo link?

**Comment by joseluishaddad** [comment]
si, me redirige al mismo link, pero me muestra otra vista:
![image](https://user-images.githubusercontent.com/20782393/63644174-ba151b80-c6b0-11e9-957a-4690dbcee18a.png)
De todas formas no me da la opción de elegir la cuenta

**Comment by joseluishaddad** [comment]
ya logré abrirlo modificando la URL a mano y agregando /u/1 después de form jajaja 
Gracias!
