### ISSUE TITLE
Contenido Control 03-09

### ISSUE THREAD

**Issue by JoacoCoyu** [PUC-Infovis/syllabus-2019#24]
Hola!

Según calendario esta semana tenemos control de lectura del paper 1, pero quería saber si será mañana o el jueves. Y respecto al paper, serían los capítulos que nos han compartido, o qué específicamente nos evaluarán. 
Gracias!

JC

**Comment by Hernan4444** [comment]
¡Hola!

Según el calendario, esta semana solo se subía el enunciado/paper del control 1 a leer, lo cual hicimos la semana pasada, pero como se mencionó en las primeras clases y sale en el calendario, la fecha de la evaluación corresponde a la misma fecha de la I1: viernes 27 de septiembre. (última columna del calendario).

Sobre los contenidos, como se mencionó en el aviso de la semana pasada, será la materia vista hasta antes de las fiestas patrias, es decir, hasta la clase de Color. Se evaluará lo que se dice en clases + ppt subidos, pero no los libros. Aunque se recomienda leerlos para complementar su estudio.

Saludos :v:

**Comment by JoacoCoyu** [comment]
Muchas gracias! Quedo clarísimo.

Saludos!
