### ISSUE TITLE
Informe E1: "¿Qué, específicamente, se implementará?"

### ISSUE THREAD

**Issue by aaguilarg** [PUC-Infovis/syllabus-2019#25]
Hola, 

Me confundió un poco esta sección del informe, a que se refiere con "¿Qué, específicamente, se implementará? ", ¿Qué seria un ejemplo de respuesta?

Gracias

**Comment by Hernan4444** [comment]
¡Hola!
Lo que queremos es una descripción de lo que implementarán ustedes en el proyecto y no lo que tomarás de internet. 

Por ejemplo, si dentro de sus propuestas está el desarrollar un gráfico de barra, esto ya está implementado, pero si ustedes deciden utilizar este idiom y conectarlo a otro gráfico (para hacer vistas coordinadas), entonces la respuesta a esta pregunta será:

> Implementaremos la coordinación entre 2 idioms: un gráfico de barra y otro idiom

Otro ejemplo puede ser que si quieren agregar un sistema para utilizar un modelo de _machine learning_ desde la página web, entonces una respuesta válida es:
> Implementaremos una API en Python que permita a nuestra página ejecutar modelos de _machine learning_ desde la API y luego desplegar los resultados en diferentes idioms.


El fin de la pregunta es pensar en el trabajo que tendrán ustedes y cual ya está listo en internet.

Saludos :v:
