### ISSUE TITLE
Proyecto E1: Utilización de Idioms

### ISSUE THREAD

**Issue by JoacoCoyu** [PUC-Infovis/syllabus-2019#26]
Hola!

Tenemos una duda en esta primera entrega respecto a la utilización de _idioms_. Cómo debe ser el formato de entrega de estos _idioms_? Se puede entregar simplemente una ilustración, o una ilustración ya con código implementado, o qué se espera?

Gracias!

JC

**Comment by Hernan4444** [comment]
¡Hola!

Lo esperado en esta entrega es que nos expliquen teóricamente (con el framework de Tamara Munzner)  los idioms. Es decir: responder al _What_, _Why_ y _How_. Un ejemplo es cómo esta imagen en donde se explica un scatterplot con las 3 preguntas:

![image](https://user-images.githubusercontent.com/15641721/64622233-5df30c80-d3bd-11e9-8d33-8383c19b8c32.png)

En relación a la ilustración que indicas, puede ser de mucha utilidad para tener una idea mejor de lo que quieren hacer, pero es opcional. Si se describe bien el idiom con las 3 preguntas será suficiente. Además, **no se espera ningún tipo de programación para esta entrega**, si ustedes ya desean poner mano en código, pueden hacerlo, pero es opcional 😄.

Destacar que en el _What_, _Why_ y _How_ deben ir todo el detalle posible de lo que se puede hacer con el idiom. Si deciden hacer una vista coordinada entre 2 idioms, deben señalar todas las tareas y how posibles. Esto no es como en el práctico 1 donde debían señalar al menos 3, sino que se esperan todos 👍 .

Saludos :v:
