### ISSUE TITLE
Proyecto E1: fecha de entrega

### ISSUE THREAD

**Issue by fivaldivia** [PUC-Infovis/syllabus-2019#27]
Hola quería saber cual es efectivamente la fecha de entrega de la entrega 1 del proyecto, ya que en la planificación del curso sale que es para el 13 de septiembre pero en el enunciado sale que es para el 12 de septiembre. Quedo atenta, muchas gracias.

**Comment by Hernan4444** [comment]
Hola,

Es hasta el 13. Actualizaré la fecha del cuestionario de inmediato.

Saludos :v:
