### ISSUE TITLE
Práctico 2: sección f

### ISSUE THREAD

**Issue by fivaldivia** [PUC-Infovis/syllabus-2019#28]
Hola quería saber a que se refiere en la letra f ) con "Betweenness", ya que no me sale eso en Graphi en la sección de Apariencia, solo me sale grado y Modularity class. Muchas gracias.

**Comment by fjlopez7** [comment]
No existe otra forma de calcular "Betweenness" ? , dado que en el video muestran que es necesario calcular la estadística de Network diameter. Donde esta estadística es la que genera problemas como lo mencionado por https://github.com/PUC-Infovis/syllabus-2019/issues/29.

**Comment by Hernan4444** [comment]
¡Hola!

No hay otra forma. Así que si se te atasca, entonces saltense ese punto y vayan por por el siguiente punto. Lo tendremos en consideración al momento de revisar el práctico.

Saludos :v:
