### ISSUE TITLE
[T01] Errores en Dataset

### ISSUE THREAD

**Issue by joseluishaddad** [PUC-Infovis/syllabus-2019#3]
Hola!, 
En cuanto a los errores para que tenemos que filtrar, estos serán solo los que aparecen en los datos que nos entregaron (negativos, `class=3.45` y `NaNs`) o algo más.
Gracias!

**Comment by eiherrera** [comment]
Hola! 
Los errores que mencionaste son los únicos posibles.
Saludos!

**Comment by yoavnavon** [comment]
@eiherrera Hola! En el training.csv hay atributos repetidos para un mismo id de planta. Por ejemplo para el ID=150, el atributo sepal_length aparece dos veces, primero con valor -7 y despues con valor -9.2. Que hacemos con estos datos? Gracias!

**Comment by eiherrera** [comment]
Hola Yoav! 
Dado que su valor es negativo tienes que borrarlos, por lo que no interfiere que se repitan.
Saludos!

**Comment by yoavnavon** [comment]
Ahh no me había fijado que en todos esos casos eran negativos.. gracias!!
