### ISSUE TITLE
Practico 2: Github Repo

### ISSUE THREAD

**Issue by MarceloSaldias** [PUC-Infovis/syllabus-2019#30]
Hola!

Olvidé que habia hecho un repo para el práctico 2 y mi compañero creó otro donde se subieron todas las cosas.
Que puedo hacer para borrar el mío? Gracias!

**Comment by Hernan4444** [comment]
Hola, 
No se puede eliminar, pero deja el repositorio vacío y con eso es suficiente.

Saludos :v:
