### ISSUE TITLE
Importar css?

### ISSUE THREAD

**Issue by naquiroz** [PUC-Infovis/syllabus-2019#34]
Podemos usar css de librerías externas?

**Comment by Hernan4444** [comment]
¡Hola!
Nos puedes dar un ejemplo de librería externa que quieras usar

Saludos

**Comment by naquiroz** [comment]
Nos gustaría usar [bulma](https://bulma.io/)

**Comment by Bobbbay** [comment]
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.css">

**Comment by Hernan4444** [comment]
Hola

Si puedes 👍 

Saludos ✌️

**Comment by naquiroz** [comment]
Gracias!

**Comment by Hernan4444** [comment]
Por favor no cierren las issues 😃  los ayudantes lo haremos en su momento.

Saludos ✌️
