### ISSUE TITLE
Uso de forEach.

### ISSUE THREAD

**Issue by jtcaraball** [PUC-Infovis/syllabus-2019#36]
Hola! Se puede utilizar el método forEach para determinar niveles de los nodos en el árbol para guiar su visualización y para cambiar atributos de varios elementos como el color o esto iría en contra del punto 4.2.2 del enunciado?

Muchas gracias!
Saludos :)

**Comment by VinceValence** [comment]
El método puede usarse para todo lo que no implique visualizar con D3. Si es que lo usan para hacer cosas como las que describes, deben justificar muy detalladamente por qué necesitaron usarlo, pues visualizar con D3 usando un ciclo (como forEach) no tiene mucha gracia, pues D3 no fue hecho con ello en mente.

Si con determinar los niveles de los nodos para guiar su visualización te refieres a que, después de entrenar un árbol, la salida de ese entrenamiento no indica explícitamente los niveles de los nodos, pero ustedes quieren obtenerlos con un forEach, pueden hacerlo. Sin embargo, si te refieres a cambiar las posiciones de los nodos en la visualización con un forEach, no está permitido. Esto se hace con el Data Join de D3.

Para lo del color, la forma más aceptada en D3 es usar [escalas de color](https://github.com/d3/d3-scale). Estas ahorran especificar de forma explícita los colores de los nodos. Teniendo el nivel de un nodo en el arreglo de datos con el que se haga un Data Join y teniendo una escala de colores, se puede indicar que se use la escala de colores en las selecciones _enter_, _update_ y/o _exit_.

Si tienen dudas de las escalas, [este _post_](https://medium.com/@mbostock/introducing-d3-scale-61980c51545f#.lk2cs7x7k) de Mike Bostock (creador de D3) los puede ayudar y para verlas en acción junto con el Data Join, [este ejemplo](https://bl.ocks.org/mbostock/b5935342c6d21928111928401e2c8608) las usa para **posiciones y color**.

Espero que esto los ayude
