### ISSUE TITLE
[T01] Duda bonus página responsive.

### ISSUE THREAD

**Issue by KnowYourselves** [PUC-Infovis/syllabus-2019#4]
Respecto al segundo bonus, se puede realizar con _bootstrap_, _materialize_, o símiles?

De antemano, gracias!

**Comment by eiherrera** [comment]
Hola!
El bonus no será considerado si utilizan una librería externa. Debe ser implementado con CSS puro.
Saludos!

**Comment by eiherrera** [comment]
También pueden usar JS para lograrlo. De igual forma, deben usar JS puro.

**Comment by Jiruiz2** [comment]
> También pueden usar JS para lograrlo. De igual forma, deben usar JS puro.

Entonces JQuery estaría prohibido?

**Comment by eiherrera** [comment]
Si, prohibido y penalizado por la ley.
