### ISSUE TITLE
[T2] Problema tooltip

### ISSUE THREAD

**Issue by fdominguezclaro** [PUC-Infovis/syllabus-2019#45]
Tengo un problema tratando de mostrar los tooltips en el árbol. Debo tener algún error muy básico pero no he logrado encontrarlo...

Usé el mismo método que la ayudantía. El elemento si se agrega al DOM, pero no se puede ver.
Alguna idea que puede ser?

Gracias!!

---

<br/>

![tooltip](https://user-images.githubusercontent.com/26119673/66675804-782e3d80-ec3c-11e9-8545-a4ba62f1b256.gif)

**Comment by Hernan4444** [comment]
¡Hola!

Algo me dice que es con la posición del div. Lo que me puede ser es que agregas un espacio entre el número de la posición y el "px". Por ejemplo: `500 px`, pero debe ser `500px`.

Avísame si era eso.
Saludos :v:

**Comment by fdominguezclaro** [comment]
Hola @Hernan4444! No, no era eso...
Saludos!

**Comment by Hernan4444** [comment]
Puedes hacer push para ver el código cuando pueda.

Saludos y quedo atento.

**Comment by fdominguezclaro** [comment]
Subido!

**Comment by Hernan4444** [comment]
¡Hola!

Pude revisar tu código y el problema es que estás creando un DIV dentro de un SVG, algo que no es posible. Recomiendo revisar la ayudantía 6/grafos en donde se crea la constante `div` y puedas identificar dónde es que estamos agregando el DIV.

Saludos :v:

**Comment by fdominguezclaro** [comment]
Ohh buenísimo!! Ahí si me resultó! 
Gracias @Hernan4444!
