### ISSUE TITLE
[E2] Uso de Framework frontend

### ISSUE THREAD

**Issue by fdominguezclaro** [PUC-Infovis/syllabus-2019#48]
Hola! 
Se puede usar React, o algún framework de front? Además de D3 obviamente.

PD: no quise mezclar la issue #43 con esto.

**Comment by Hernan4444** [comment]
Hola, si pueden!!
Solo tengan cuidado que react y D3 tienen formas particulares de modificar el DOM y eso puede generarles algunos problemas (que se pueden solucionar, pero con un poco más de investigación). Por lo tanto, pueden udar React o cualquier otro framework de frontend con D3, pero bajo su propio riesgo.

Saludos :v:
