### ISSUE TITLE
[T03] Calcular métricas

### ISSUE THREAD

**Issue by nimorales97** [PUC-Infovis/syllabus-2019#62]
Estoy haciendo la tarea 3 basándome en el código de la [Ayudantía de FDG](https://observablehq.com/@hernan4444/graph-force) y tengo problemas para calcular las métricas usando las funciones que me dan en el [Readme](https://observablehq.com/@hernan4444/ejemplo-usando-gephi) de la tarea, porque en ese caso se le están aplicando las funciones a un grafo entero que está guardado en una variable _g_
![image](https://user-images.githubusercontent.com/30670006/69674715-d2b01b80-107b-11ea-8a07-21cafc4b711f.png)
En cambio mi código exporta un json, y tiene unas variables _container_ (una es una variable como tal donde se agrega un SVG y las otras están dentro de un .then(dataset =>{ ... }) y no sé qué hace exactamente con los links ni por qué es distinto del de los nodos)
![image](https://user-images.githubusercontent.com/30670006/69674461-443b9a00-107b-11ea-92f0-b7a689ee1382.png)

Cómo puedo saber qué entregarle a la función o qué cambiar en mi código para que funcione? Intenté con dataset, container, nodes, node.id y no sé en verdad qué tengo que darle a la función en lugar del _g_.
De antemano gracias!

**Comment by Hernan4444** [comment]
Hola,

Tienes que hacer un preprocesamiento con javascript para iterar por dataset.links y crear un "g" como está en el código y luego pasarle ese "g" a las funciones, pero no existe otra forma de hacer funcionar las funciones si no es con un "g".

Saludos :v:

**Comment by nimorales97** [comment]
> Hola,
> 
> Tienes que hacer un preprocesamiento con javascript para iterar por dataset.links y crear un "g" como está en el código y luego pasarle ese "g" a las funciones, pero no existe otra forma de hacer funcionar las funciones si no es con un "g".
> 
> Saludos

Entiendo, muchas gracias!
