### ISSUE TITLE
Ayudantes para preguntas Control 1?

### ISSUE THREAD

**Issue by naquiroz** [PUC-Infovis/syllabus-2019#63]
Hola! Habrán ayudantes durante el control 1 para hacer preguntas?

**Comment by Hernan4444** [comment]
Hola, 

Habrá un ayudante en la sala mañana de 10 a 11:30 para responder dudas. También estará presente el profesor con Zoom en la sala, así los que no puedan asistir puedan hablar con el mismo profesor mediante el chat.

Saludos :v:

**Comment by naquiroz** [comment]
Gracias!
