### ISSUE TITLE
[T01] - Citar Código

### ISSUE THREAD

**Issue by KnowYourselves** [PUC-Infovis/syllabus-2019#9]
Hola!

Para efectos de la página web, podemos citar código que encontremos que nos sea útil? (por ejemplo, una navbar, un slideshow, etc, etc)

**Comment by Hernan4444** [comment]
Hola, 

Si puedes, solo recuerda que para efectos de esta tarea, no está permitido usar librerías de javascript, sino javascript puro, y es muuuy probable que los códigos de internet usen al menos JQuery. Si el código utilizado no hace eso, todo bien n.n

Saludos :v:
Hernán V.
